### ISSUE TITLE
Fill the format with file extension

### ISSUE THREAD

**Issue by fanich37** [valtlai/postcss-font-format-keywords#1]
Just a question: is it possible to fill the format from file extension?

**Comment by valtlai** [comment]
That’s very cool idea, but non-standard and not in the scope of this plugin. This plugin is meant to be polyfill for the standard CSS feature, so that the plugin can be dropped in the future, when the browser support is wide enough, and the CSS will just work as it.

Maybe somebody else could create another extension for the behavior you described? (Personally I only use PostCSS plugins for future CSS features and minification.)

**Comment by fanich37** [comment]
Thank you for the explanation :)
